name: Analytics-Service
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
       - name: List files
         run: ls -l
       - name: Build image
         run: make docker-build

      
      
